### ISSUE TITLE
Je hoeft niet elk element een CSS class te geven als je parent element al een CSS class heeft

### ISSUE THREAD

**Issue by JeroenHeemskerk** [lonne-lee/educom-webshop-basis#18]
Ik zie hier dat je verschillende .navbar classen hebt 
https://github.com/lonne-lee/educom-webshop-basis/blob/74924eb41fefb84002eb6244f902240cdb5f4f38/CSS/stylesheet.css#L9-L22

In de code zie ik dat je zowel de `<div>` als de `<ul>` als de `<li>` een class navbar hebt gegeven:
https://github.com/lonne-lee/educom-webshop-basis/blob/74924eb41fefb84002eb6244f902240cdb5f4f38/about.html#L10-L17
Dit is niet nodig, als je het alsvolgt opzet:'
```html
<!--navgiation bar--> 
 <div class="navbar">  
     <ul> 
         <li><a href="index.html">HOME</a></li> 
         <li><a href="about.html">ABOUT</a></li> 
         <li><a href="contact.html">CONTACT</a></li> 
      </ul> 
 </div> 
```

kun je je CSS alsvolgt gebruiken
```css
 .navbar /* Navigation */{ 
     background: blue;
 } 
  
 .navbar ul { 
     list-style-type: none; 
     margin: 0; 
     padding: 0; 
 } 
  
 .navbar ul li { 
     float: left; 
 } 
```
